### ISSUE TITLE
Distinguish between primary and secondary ports/adapters

### ISSUE THREAD

**Issue by lbragaglia** [matteobaglini/onion-with-functional-programming#2]
This slide in the _"Split domain from infrastructure"_ section:

> DIP into Onion
> - Inner layers define interfaces (Ports)
> - Outer layers implement interfaces (Adapters)

can be misleading.

This is surely true for **secondary** ports/adapters, indeed, in the example you end up building two _secondary ports/adapters_ (`employeeRepository` and `messageGateway`).

But the _primary port_ (`sendGreetings`)  isn't an interface and the _primary adapter_ (`main`) doesn't implement any. Or better said, the _primary adapter_ implements the implicit contract of a console application's entry point.

**Comment by matteobaglini** [comment]
Sorry for the late response. You are completely right. :raised_hands:

I did it to simplify the concept and, in particular, because in 90% of the cases that I have implemented the Onion I have never needed to explicit the primary port to get the benefits of this architecture.

I will fix the slide for future presentations.

I really appreciate this kind of feedback. :relaxed:
